/**
 * @file types.ts
 * @description Phase 11: Revenue Distribution — Types & Interface Specifications
 *
 * Defines the configurable allocation policy, settlement inputs, distribution
 * results, audit records, and role authorization types for distributing realized
 * arbitrage profits across Trading Capital, Reserve, and Business/Protocol Revenue.
 */

import { SupportedChainId } from "../types";

/**
 * Three-bucket allocation policy in Basis Points (10000 bps = 100%).
 * Configurable with optional minimum and maximum bounds.
 */
export interface ThreeBucketAllocationPolicy {
  /** Trading Capital share in basis points (e.g., 6000 bps = 60%) */
  tradingCapitalBps: number;
  /** Reserve share in basis points (e.g., 2000 bps = 20%) */
  reserveBps: number;
  /** Business / Protocol Revenue share in basis points (e.g., 2000 bps = 20%) */
  revenueBps: number;

  // Optional bounds
  minTradingCapitalBps?: number;
  maxTradingCapitalBps?: number;
  minReserveBps?: number;
  maxReserveBps?: number;
  minRevenueBps?: number;
  maxRevenueBps?: number;
}

/**
 * Default initial allocation policy:
 * 60% -> Trading Capital
 * 20% -> Reserve
 * 20% -> Revenue
 */
export const DEFAULT_ALLOCATION_POLICY: ThreeBucketAllocationPolicy = {
  tradingCapitalBps: 6000, // 60%
  reserveBps: 2000,        // 20%
  revenueBps: 2000,        // 20%
  minTradingCapitalBps: 1000, // min 10%
  maxTradingCapitalBps: 9000, // max 90%
  minReserveBps: 500,         // min 5%
  maxReserveBps: 5000,        // max 50%
  minRevenueBps: 500,         // min 5%
  maxRevenueBps: 5000,        // max 50%
};

/**
 * Basis points denominator (100.00%)
 */
export const BPS_DENOMINATOR = 10000n;

/**
 * Confirmed arbitrage execution trade settlement input.
 */
export interface TradeSettlementInput {
  /** Unique trade identifier */
  tradeId: string | number;
  /** Execution transaction hash */
  txHash: string;
  /** Chain where trade was executed */
  chainId: SupportedChainId;
  /** Asset token address (e.g. USDT/USDC) */
  token: string;
  /** Asset decimals (defaults to 18) */
  tokenDecimals?: number;
  /** Gross profit generated by arbitrage */
  grossProfit: bigint;
  /** Total DEX swap fees incurred */
  dexFees: bigint;
  /** Total transaction gas cost incurred */
  gasCost: bigint;
  /** Any additional operational or relay costs */
  otherCosts?: bigint;
  /** Confirmed realized net profit from execution receipt/treasury */
  confirmedRealizedNetProfit?: bigint;
  /** Must be true for distribution; false rejects as unrealized profit */
  isConfirmed: boolean;
}

/**
 * Detailed breakdown of integer calculations and dust handling.
 */
export interface DistributionCalculation {
  grossProfit: bigint;
  totalCosts: bigint;
  realizedNetProfit: bigint;
  tradingCapitalAllocation: bigint;
  reserveAllocation: bigint;
  revenueAllocation: bigint;
  dustAmount: bigint;
  formatted: {
    grossProfit: number;
    totalCosts: number;
    realizedNetProfit: number;
    tradingCapital: number;
    reserve: number;
    revenue: number;
    tradingCapitalPct: number;
    reservePct: number;
    revenuePct: number;
  };
}

/**
 * Status of a distribution attempt.
 */
export type DistributionStatus =
  | "DISTRIBUTED"
  | "REJECTED_ZERO_PROFIT"
  | "REJECTED_NEGATIVE_PROFIT"
  | "REJECTED_UNCONFIRMED"
  | "REJECTED_INVALID_POLICY";

/**
 * Formal distribution result record stored in accounting ledger.
 */
export interface DistributionResult {
  tradeId: string | number;
  txHash: string;
  chainId: SupportedChainId;
  token: string;
  realizedNetProfit: bigint;
  realizedNetProfitFormatted: number;
  tradingAllocation: bigint;
  tradingAllocationFormatted: number;
  reserveAllocation: bigint;
  reserveAllocationFormatted: number;
  revenueAllocation: bigint;
  revenueAllocationFormatted: number;
  allocationPercentages: {
    tradingCapitalPct: number;
    reservePct: number;
    revenuePct: number;
  };
  timestamp: number;
  status: DistributionStatus;
  rejectionReason?: string;
}

/**
 * Audit log entry for allocation policy modifications.
 */
export interface PolicyUpdateRecord {
  updatedBy: string;
  previousPolicy: ThreeBucketAllocationPolicy;
  newPolicy: ThreeBucketAllocationPolicy;
  timestamp: number;
  txHash?: string;
}

/**
 * Revenue withdrawal validation input.
 */
export interface RevenueWithdrawalValidation {
  callerAddress: string;
  callerRole: "ADMIN" | "TREASURY_MANAGER" | "ARBITRAGE_EXECUTOR" | "ANONYMOUS";
  token: string;
  amount: bigint;
  availableRevenue: bigint;
  isPaused: boolean;
}
